import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Kaka",
      email: "kakaadmin@gmail.com",
      password: bcrypt.hashSync("12345"),
      isAdmin: true,
    },
    {
      name: "Vatija",
      email: "vatija@gmail.com",
      password: bcrypt.hashSync("1234"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "Nike slim shirts",
      slug: "nike-slim-shirts",
      category: "Shirts",
      image: "/images/slim1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "premium quality",
    },
    {
      // _id: "2",
      name: "Addidas slim fit",
      slug: "addidas-slim-fit",
      category: "Shirts",
      image: "/images/slim2.jpg",
      price: 225,
      countInStock: 0,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "premium quality cotton",
    },
    {
      // _id: "3",
      name: "Addias slim jersy",
      slug: "addias-slim-jersy",
      category: "Jersy",
      image: "/images/Arg.jpg",
      price: 350,
      countInStock: 10,
      brand: "Addidas",
      rating: 5,
      numReviews: 5,
      description: "premium quality cotton",
    },
    {
      // _id: "4",
      name: "Barca New Home Kit",
      slug: "barca-jersy-new",
      category: "Jersy",
      image: "/images/barca.jpg",
      price: 300,
      countInStock: 10,
      brand: "Spotify",
      rating: 5,
      numReviews: 5,
      description: "premium quality jersy",
    },
  ],
};
export default data;
