const data = {
  products: [
    {
      name: "Nike-slim shirts",
      slug: "nike-slim-shirts",
      category: "Shirts",
      image: "/images/slim1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "premium quality",
    },
    {
      name: "Addidas-slim-fit",
      slug: "addidas-slim-fit",
      category: "Shirts",
      image: "/images/slim2.jpg",
      price: 225,
      countInStock: 10,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "premium quality cotton",
    },
    {
      name: "Addias-slim-jersy",
      slug: "addias-slim-jersy",
      category: "Jersy",
      image: "/images/Arg.jpg",
      price: 350,
      countInStock: 10,
      brand: "Addidas",
      rating: 5,
      numReviews: 5,
      description: "premium quality cotton",
    },
    {
      name: "Barca-jersy",
      slug: "barca-jersy-new",
      category: "Jersy",
      image: "/images/barca.jpg",
      price: 300,
      countInStock: 10,
      brand: "Spotify",
      rating: 5,
      numReviews: 5,
      description: "premium quality jersy",
    },

    {
      name: "kaka-jersy",
      slug: "kaka-jersy-new",
      category: "Jersy",
      image: "/images/barca.jpg",
      price: 300,
      countInStock: 10,
      brand: "Spotify",
      rating: 5,
      numReviews: 5,
      description: "premium quality jersy",
    },

    {
      // _id: "4",
      name: "kaka Kit 2",
      slug: "kaka-jersy-new-2",
      category: "Jersy",
      image: "/images/aa.jpg",
      price: 300,
      countInStock: 10,
      brand: "Spotify",
      rating: 5,
      numReviews: 5,
      description: "premium quality jersy",
    },
  ],
};
export default data;
